frr version 9.1.3_git
frr defaults traditional
hostname edge2
domainname localdomain
log syslog informational
service integrated-vtysh-config
!
ip route 0.0.0.0/0 10.1.0.1
ip route 10.99.0.1/32 10.2.0.20
ipv6 route ::/0 fd00:1::1
ipv6 route fd00:99::1/128 fd00:2::20
!
interface eth1
 description isp-segment
 ip address 10.1.0.12/24
 ipv6 address fd00:1::12/64
exit
!
interface eth2
 description dmz-segment
 ip address 10.2.0.12/24
 ipv6 address fd00:2::12/64
exit
!
router bgp 65002
 bgp router-id 10.1.0.12
 no bgp ebgp-requires-policy
 neighbor 10.1.0.1 remote-as 65000
 neighbor 10.1.0.1 description isp
 neighbor fd00:1::1 remote-as 65000
 neighbor fd00:1::1 description isp-v6
 !
 address-family ipv4 unicast
  network 10.99.0.1/32
  no neighbor fd00:1::1 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network fd00:99::1/128
  neighbor fd00:1::1 activate
 exit-address-family
exit
!
