worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 256; }

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;
    server_tokens off;

    server {
        listen 80;
        listen [::]:80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
