frr version 9.1.3_git
frr defaults traditional
hostname isp
domainname localdomain
log syslog informational
service integrated-vtysh-config
!
interface eth1
 description uplink-client
 ip address 1.1.1.1/24
 ipv6 address fd00::1/64
exit
!
interface eth2
 description edge-segment
 ip address 10.1.0.1/24
 ipv6 address fd00:1::1/64
exit
!
router bgp 65000
 bgp router-id 10.1.0.1
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor 10.1.0.11 remote-as 65001
 neighbor 10.1.0.11 description edge1
 neighbor 10.1.0.12 remote-as 65002
 neighbor 10.1.0.12 description edge2
 neighbor fd00:1::11 remote-as 65001
 neighbor fd00:1::11 description edge1-v6
 neighbor fd00:1::12 remote-as 65002
 neighbor fd00:1::12 description edge2-v6
 !
 address-family ipv4 unicast
  no neighbor fd00:1::11 activate
  no neighbor fd00:1::12 activate
  maximum-paths 2
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fd00:1::11 activate
  neighbor fd00:1::12 activate
  maximum-paths 2
 exit-address-family
exit
!
